---
title: Expositus
description: 'My personal blog where I post about programming as well as other topics.'

email: flyingfischy@gmail.com
twitter_username: flyingfisch_
github_username: flyingfisch

defaults:
  - scope:
      path: ''
    values:
      author: Mark Fischer, Jr.

baseurl: ''
url: https://markfischerjr.com/

exclude:
- README.md

keep_files:
- README.md
- ".git"

markdown: kramdown

redcarpet:
  extensions:
  - fenced_code_blocks

kramdown:
  auto_ids: true

pagination:
  enabled: true
  per_page: 3
  sort_reverse: true

plugins:
- jekyll_figure
- jekyll-paginate-v2

figures:
  dir: '/assets'
  enumerate: true
