---
title: Expositus
description: My personal blog where I post about programming as well as other topics.
url: http://markfischerjr.com/
timezone: UTC
email: flyingfisch@toppagedesign.com
twitter_username: flyingfisch_
github_username: flyingfisch

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ""
  values:
    author: Mark Fischer, Jr.

exclude:
- README.md
- Rakefile
- vendor/bundle

redcarpet:
  extensions:
  - fenced_code_blocks

markdown: kramdown
kramdown:
  auto_ids: true

paginate: 3

figures:
  dir: "/assets/figures"
  enumerate: true
