---
upload_path: "/assets/:year:/:month:/:day:"
frontmatter_file_url_template: "/assets/:year:/:month:/:day:"
body_file_url_template: "/assets/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections: 
