---
pages:
- _posts/2018-03-20-automated-testing-with-mstest-and-selenium.md
- _posts/2018-02-22-an-updated-thought-on-self-documenting-code.md
- _posts/2018-02-22-poetry.md
- _posts/visual-studio-code.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: Invalid date
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: post
- name: author
  label: Author
  type: text
  hidden: false
  default: Mark Fischer, Jr.
  config:
    required: false
