---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: now
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: post
- name: author
  label: Author
  type: text
  hidden: false
  default: Mark Fischer, Jr.
  config:
    required: false
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
pages:
- _posts/2018-02-22-poetry.md
- _posts/2018-03-20-automated-testing-with-mstest-and-selenium.md
- _posts/2018-03-21-weird-tfs-error-message.md
- _posts/2018-04-09-grocery-stores-are-broken.md
- _posts/2019-09-06-sharpie-stainless-steel-pen-refill-hack.md
- _posts/open-id-auth0-redirecting-to-logout-page-directly-after-logging-in.md
